# Generated by Django 6.0.1 on 2026-01-20 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20, unique=True)),
                ('categoria', models.CharField(choices=[('A', 'Moto'), ('B', 'Carro'), ('AB', 'Carro e Moto')], default='B', max_length=2)),
                ('aulas_carro_realizadas', models.IntegerField(blank=True, default=0, null=True)),
                ('aulas_moto_realizadas', models.IntegerField(blank=True, default=0, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aula', models.DateTimeField()),
                ('descricao', models.TextField(blank=True, null=True)),
                ('realizada', models.BooleanField(default=False)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='alunos.aluno')),
            ],
        ),
    ]
